Update gamescope-session-script to expose Display color adjustment button.

diff --git a/rootfs/usr/share/gamescope-session/gamescope-session-script b/rootfs/usr/share/gamescope-session/gamescope-session-script
--- a/rootfs/usr/share/gamescope-session/gamescope-session-script
+++ b/rootfs/usr/share/gamescope-session/gamescope-session-script
@@ -1,15 +1,14 @@
 #!/bin/bash
 
-# Fix intel color corruption
-# might come with some performance degradation but is better than a corrupted
-# color image
-export INTEL_DEBUG=norbc
-export mesa_glthread=true
-
-# Some environment variables by default (taken from Deck session)
+##
+## Session globals
+##
 export SDL_VIDEO_MINIMIZE_ON_FOCUS_LOSS=0
 
-# Enable Mangoapp
+export HOMETEST_DESKTOP=1
+export HOMETEST_DESKTOP_SESSION=plasma
+
+export STEAM_MANGOAPP_PRESETS_SUPPORTED=1
 export STEAM_USE_MANGOAPP=1
 export MANGOHUD_CONFIGFILE=$(mktemp /tmp/mangohud.XXXXXXXX)
 
@@ -18,17 +17,7 @@ export RADV_FORCE_VRS_CONFIG_FILE=$(mktemp /tmp/radv_vrs.XXXXXXXX)
 
 # Plop GAMESCOPE_MODE_SAVE_FILE into $XDG_CONFIG_HOME (defaults to ~/.config).
 export GAMESCOPE_MODE_SAVE_FILE="${XDG_CONFIG_HOME:-$HOME/.config}/gamescope/modes.cfg"
-
-# Make path to gamescope mode save file.
-mkdir -p "$(dirname "$GAMESCOPE_MODE_SAVE_FILE")"
-touch "$GAMESCOPE_MODE_SAVE_FILE"
-#echo "Making Gamescope Mode Save file at \"$GAMESCOPE_MODE_SAVE_FILE\""
-
-# Support for gamescope tearing with GAMESCOPE_ALLOW_TEARING atom
-export STEAM_GAMESCOPE_HAS_TEARING_SUPPORT=1
-
-# Enable tearing controls in steam
-export STEAM_GAMESCOPE_TEARING_SUPPORTED=1
+export GAMESCOPE_PATCHED_EDID_FILE="${XDG_CONFIG_HOME:-$HOME/.config}/gamescope/edid.bin"
 
 # There is no way to set a color space for an NV12
 # buffer in Wayland. And the color management protocol that is
@@ -36,6 +25,18 @@ export STEAM_GAMESCOPE_TEARING_SUPPORTED=1
 # So just workaround this with an ENV var that Remote Play Together
 # and Gamescope will use for now.
 export GAMESCOPE_NV12_COLORSPACE=k_EStreamColorspace_BT601
+
+export STEAM_GAMESCOPE_HDR_SUPPORTED=1
+
+# Make path to gamescope mode save file.
+mkdir -p "$(dirname "$GAMESCOPE_MODE_SAVE_FILE")"
+touch "$GAMESCOPE_MODE_SAVE_FILE"
+echo "Making Gamescope Mode Save file at \"$GAMESCOPE_MODE_SAVE_FILE\""
+
+# Make path to Gamescope edid patched file.
+mkdir -p "$(dirname "$GAMESCOPE_PATCHED_EDID_FILE")"
+touch "$GAMESCOPE_PATCHED_EDID_FILE"
+echo "Making Gamescope patched edid at \"$GAMESCOPE_PATCHED_EDID_FILE\""
 
 # Initially write no_display to our config file
 # so we don't get mangoapp showing up before Steam initializes
@@ -48,15 +49,33 @@ echo "no_display" > "$MANGOHUD_CONFIGFILE"
 mkdir -p "$(dirname "$RADV_FORCE_VRS_CONFIG_FILE")"
 echo "1x1" > "$RADV_FORCE_VRS_CONFIG_FILE"
 
-# To expose vram info from radv
+# Let's try this across the board to see if it breaks anything
+# Helps performance in HZD, Cyberpunk, at least
+# Expose 8 physical cores, instead of 4c/8t
+export WINE_CPU_TOPOLOGY=16:0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15
+
+# To expose vram info from radv's patch we're including
 export WINEDLLOVERRIDES=dxgi=n
 
-# Workaround for steam getting killed immediatly during reboot
-export STEAMOS_STEAM_REBOOT_SENTINEL="/tmp/steamos-reboot-sentinel"
+# Catch reboot and poweroof sentinels here
+if [[ -e "$STEAMOS_STEAM_REBOOT_SENTINEL" ]]; then
+	rm -f "$STEAMOS_STEAM_REBOOT_SENTINEL"
+	# rearm short session tracker
+	rm "$short_session_tracker_file"
+	reboot
+fi
+if [[ -e "$STEAMOS_STEAM_SHUTDOWN_SENTINEL" ]]; then
+	rm -f "$STEAMOS_STEAM_SHUTDOWN_SENTINEL"
+	# rearm short session tracker
+	rm "$short_session_tracker_file"
+	poweroff
+fi
 
-# Workaround for steam getting killed immediatly during shutdown
-# Same idea as reboot sentinel above
-export STEAMOS_STEAM_SHUTDOWN_SENTINEL="/tmp/steamos-shutdown-sentinel"
+# Enable dynamic backlight, we have the kernel patch to disable events
+export STEAM_ENABLE_DYNAMIC_BACKLIGHT=1
+
+# Enabled fan control toggle in steam
+export STEAM_ENABLE_FAN_CONTROL=1
 
 # Enable volume key management via steam for this session
 export STEAM_ENABLE_VOLUME_HANDLER=1
@@ -73,14 +92,26 @@ export STEAM_MULTIPLE_XWAYLANDS=1
 # We have the Mesa integration for the fifo-based dynamic fps-limiter
 export STEAM_GAMESCOPE_DYNAMIC_FPSLIMITER=1
 
-# We have gamma/degamma exponent support
-export STEAM_GAMESCOPE_COLOR_TOYS=1
+# Support for gamescope tearing with GAMESCOPE_ALLOW_TEARING atom
+export STEAM_GAMESCOPE_HAS_TEARING_SUPPORT=1
 
 # We have NIS support
 export STEAM_GAMESCOPE_NIS_SUPPORTED=1
 
+# Enable tearing controls in steam
+export STEAM_GAMESCOPE_TEARING_SUPPORTED=1
+
+# Enable VRR controls in steam
+export STEAM_GAMESCOPE_VRR_SUPPORTED=1
+
+# When set to 1, a toggle will show up in the steamui to control whether dynamic refresh rate is applied to the steamui
+export STEAM_GAMESCOPE_DYNAMIC_REFRESH_IN_STEAM_SUPPORTED=0
+
 # Don't wait for buffers to idle on the client side before sending them to gamescope
 export vk_xwayland_wait_ready=false
+
+# Set refresh rate range and enable refresh rate switching
+export STEAM_DISPLAY_REFRESH_LIMITS=40,60
 
 # Let steam know it can unmount drives without superuser privileges
 export STEAM_ALLOW_DRIVE_UNMOUNT=1
@@ -94,42 +125,75 @@ export STEAM_MANGOAPP_HORIZONTAL_SUPPORTED=1
 # Scaling support
 export STEAM_GAMESCOPE_FANCY_SCALING_SUPPORT=1
 
+# Color management support
+export STEAM_GAMESCOPE_COLOR_MANAGED=1
+export STEAM_GAMESCOPE_VIRTUAL_WHITE=1
+
 # Set input method modules for Qt/GTK that will show the Steam keyboard
 export QT_IM_MODULE=steam
 export GTK_IM_MODULE=Steam
 
+# Make Qt apps use the styling and behaviour of the desktop session
+# This fixes some missing icons and unreadable text with Qt desktop apps in gamescope
+export QT_QPA_PLATFORM_THEME=kde
+
+# TODO!
+# Bring this back when gamescope side is more complete
+#
+# Remove vsync handling from Xwayland, we handle it in gamescope
+#export vblank_mode=0
+#export MESA_VK_WSI_PRESENT_MODE=immediate
+
 # To play nice with the short term callback-based limiter for now
 export GAMESCOPE_LIMITER_FILE=$(mktemp /tmp/gamescope-limiter.XXXXXXXX)
 
-# Use SteamOS background if exists
-if [ -f "/usr/share/steamos/steamos.png" ] ; then
-  export STEAM_UPDATEUI_PNG_BACKGROUND=/usr/share/steamos/steamos.png
-fi
+export XCURSOR_THEME=steam
+
+# Workaround for Steam login issue while Steam client change propagates out of Beta
+touch ~/.steam/root/config/SteamAppData.vdf || true
+
+export STEAM_UPDATEUI_PNG_BACKGROUND=/usr/share/steamos/steamos.png
 
 ulimit -n 524288
 
-# Source device quirks if exists
-if [ -f /usr/share/gamescope-session/device-quirks ]; then
-  . /usr/share/gamescope-session/device-quirks
-fi
-
-# Source environment from ~/.config/environment.d with user overrides
-set -a
-for i in "${HOME}"/.config/environment.d/*.conf ;
-do
-    [[ -f "${i}" ]] && . "${i}"
-done
-set +a
-
-# Setup socket for gamescope
 # Create run directory file for startup and stats sockets
+#   shellcheck disable=SC2030 # (broken warning)
 tmpdir="$([[ -n ${XDG_RUNTIME_DIR+x} ]] && mktemp -p "$XDG_RUNTIME_DIR" -d -t gamescope.XXXXXXX)"
 socket="${tmpdir:+$tmpdir/startup.socket}"
 stats="${tmpdir:+$tmpdir/stats.pipe}"
 # Fail early if we don't have a proper runtime directory setup
+#   shellcheck disable=SC2031 # (broken warning)
 if [[ -z $tmpdir || -z ${XDG_RUNTIME_DIR+x} ]]; then
 	echo >&2 "!! Failed to find run directory in which to create stats session sockets (is \$XDG_RUNTIME_DIR set?)"
 	exit 0
+fi
+
+# 1048576 = 1M - passing it like that omits the 'M' suffix - xargs removes whitespace
+free_disk_space_megs=$(df ~/ --output=avail -B1048576 | sed -n '2 p' | xargs)
+minimum_free_disk_space_needed_megs=500
+
+if [[ "$free_disk_space_megs" -lt "$minimum_free_disk_space_needed_megs" ]]; then
+	echo >&2 "gamescope-session: not enough disk space to proceed, trying to find game to delete"
+
+	find ~/.local/share/Steam/steamapps/common/ -mindepth 1 -maxdepth 1 -type d -printf "%T@ %p\0" | sort -n -z | while IFS= read -r -d $'\0' line; do
+		timestamp=${line%% *}
+                game_folder=${line#* }
+
+		[[ -d $game_folder ]]  || continue
+
+		acf=$(grep -F -- "$(basename -- "$game_folder")" ~/.local/share/Steam/steamapps/*.acf | grep \"installdir\" | cut -d: -f1)
+		[[ -e "$acf" ]] || continue
+
+		echo >&2 "gamescope-session: deleting $(basename "$game_folder")"
+		appid=$(basename "$acf" | cut -d_ -f2 | cut -d. -f1)
+
+		# TODO leave a note for Steam to display UI to explain what happened, if this logic stays
+		# intentionally leave compatdata; could be unclouded save files there
+		rm -rf --one-file-system -- "$game_folder" "$acf" ~/.local/share/Steam/steamapps/shadercache/"$appid"
+
+		free_disk_space_megs=$(df ~/ --output=avail -B1048576 | sed -n '2 p' | xargs)
+		[[ "$free_disk_space_megs" -lt "$minimum_free_disk_space_needed_megs" ]] || break
+	done
 fi
 
 export GAMESCOPE_STATS="$stats"
@@ -148,98 +212,36 @@ if flock -n 9 && rm -f "$sessionlink" && ln -sf "$tmpdir" "$sessionlink"; then
 else
 	echo >&2 "!! Failed to claim global gamescope stats session"
 fi
+# Define orientation here
+DEVICENAME=$(cat /sys/devices/virtual/dmi/id/product_name)
+# OXP Devices
+OXP_LIST="ONE XPLAYER:ONEXPLAYER 1 T08:ONEXPLAYER 1S A08:ONEXPLAYER 1S T08:ONEXPLAYER mini A07:ONEXPLAYER mini GA72:ONEXPLAYER mini GT72:ONEXPLAYER GUNDAM GA72:ONEXPLAYER 2 ARP23:ONEXPLAYER Mini Pro"
+# AYANEO AIR Devices
+AIR_LIST="AIR:AIR Pro"
+# AOKZOE Devices
+AOK_LIST="AOKZOE A1 AR07"
 
-# Use cursor if file exist
-if [ -z "$CURSOR_FILE" ] ; then
-    CURSOR_FILE="${HOME}/.local/share/Steam/tenfoot/resource/images/cursors/arrow_right.png"
-fi
-CURSOR=""
-if [ -f "$CURSOR_FILE" ] ; then
-    CURSOR="--cursor ${CURSOR_FILE}"
-fi
-
-# Define session if not overriden
-if [ -z "$STEAMCMD" ] ; then
-    STEAMCMD="steam -gamepadui -steamos3 -steampal -steamdeck"
-fi
-
-if [ -z "$GAMESCOPECMD" ] ; then
-    RESOLUTION=""
-    if [ -n "$SCREEN_WIDTH" ] && [ -n "$SCREEN_HEIGHT" ] ; then
-        RESOLUTION="-W $SCREEN_WIDTH -H $SCREEN_HEIGHT"
-    fi
-    
-    if [ -z $VULKAN_ADAPTER ]; then
-        GAMESCOPECMD="/usr/bin/gamescope \
-        $CURSOR \
-        -e \
-        $RESOLUTION \
-        --xwayland-count 2 \
-        -O *,eDP-1 \
-        --default-touch-mode 4 \
-        --hide-cursor-delay 3000 \
-        --fade-out-duration 200 \
-        -R $socket -T $stats"
-     else
-        GAMESCOPECMD="/usr/bin/gamescope \
-        $CURSOR \
-        -e \
-        $RESOLUTION \
-        --xwayland-count 2 \
-        -O *,eDP-1 \
-        --default-touch-mode 4 \
-        --hide-cursor-delay 3000 \
-        --fade-out-duration 200 \
-        --prefer-vk-device $VULKAN_ADAPTER \
-        -R $socket -T $stats"
-     fi
-
-else
-    # Add socket and stats read
-    if [ -z $VULKAN_ADAPTER ]; then
-        GAMESCOPECMD+=" -R $socket -T $stats"
-    else
-        GAMESCOPECMD+=" --prefer-vk-device $VULKAN_ADAPTER -R $socket -T $stats"
-    fi
-    
+if [[ ":$OXP_LIST:" =~ ":$DEVICENAME:"  ]]; then
+    DEVICEORIENTATION="--force-orientation left"
+elif [[ ":$AIR_LIST:" =~ ":$DEVICENAME:"  ]]; then
+    DEVICEORIENTATION="--force-orientation left"
+elif [[ ":$AOK_LIST:" =~ ":$DEVICENAME:"  ]]; then
+    DEVICEORIENTATION="--force-orientation left"
 fi
 
-# Workaround for Steam login issue while Steam client change propagates out of Beta
-touch "${HOME}"/.steam/root/config/SteamAppData.vdf || true
-
-# Atempt to fallback to a desktop session if something goes wrong too many times
-short_session_tracker_file="/tmp/chimeraos-short-session-tracker"
-short_session_duration=60
-short_session_count_before_reset=3
-SECONDS=0
-
-short_session_count=$(< "$short_session_tracker_file" wc -l)
-
-if [[ "$short_session_count" -ge "$short_session_count_before_reset" ]]; then
-    echo >&2 "gamescope-session: detected broken Steam or gamescope failure, will try to reset the session"
-    mkdir -p ~/.local/share/Steam
-    # remove some caches and stateful things known to cause Steam to fail to start if corrupt
-    rm -rf --one-file-system ~/.local/share/Steam/config/widevine
-    # change session to desktop as fallback
-    steamos-session-select desktop
-    # rearm
-    rm "$short_session_tracker_file"
-    exit 1
-fi
-
-# Log rotate the last session
-if [ -f "${HOME}"/.steam-tweaks.log ]; then
-    cp "${HOME}"/.steam-tweaks.log "${HOME}"/.steam-tweaks.log.old
-fi
-if [ -f "${HOME}"/.steam-stdout.log ]; then
-    cp "${HOME}"/.steam-stdout.log "${HOME}"/.steam-stdout.log.old
-fi
-if [ -f "${HOME}"/.gamescope-stdout.log ]; then
-    cp "${HOME}"/.gamescope-stdout.log "${HOME}"/.gamescope-stdout.log.old
-fi
-
-# Start gamescope compositor, log it's output and background it
-$GAMESCOPECMD > "${HOME}"/.gamescope-stdout.log 2>&1 &
+gamescope \
+	--generate-drm-mode fixed \
+	--xwayland-count 2 \
+	-w 1280 -h 800 \
+    ${DEVICEORIENTATION} \
+	--default-touch-mode 4 \
+	--hide-cursor-delay 3000 \
+	--max-scale 2 \
+	--fade-out-duration 200 \
+	-e -R "$socket" -T "$stats" \
+	-O '*',eDP-1 \
+	--cursor-hotspot 5,3 --cursor /usr/share/steamos/steamos-cursor.png \
+	&
 gamescope_pid="$!"
 
 if read -r -t 3 response_x_display response_wl_display <> "$socket"; then
@@ -247,57 +249,78 @@ if read -r -t 3 response_x_display response_wl_display <> "$socket"; then
 	export GAMESCOPE_WAYLAND_DISPLAY="$response_wl_display"
 	# We're done!
 else
-	echo "gamescope failed" >> "$short_session_tracker_file"
 	kill -9 "$gamescope_pid"
 	wait
-	exit 1
-	# Systemd or Session manager will have to restart session
+	exit 0
+	# SDDM will restart us
 fi
 
-# Run steam-tweaks if exists
-if command -v steam-tweaks > /dev/null; then
-    steam-tweaks > "${HOME}"/.steam-tweaks.log
+xbindkeys -f /etc/xbindkeysrc
+
+steamargs=("-steamos3" "-steampal" "-steamdeck" "-gamepadui")
+
+# Input method support
+/usr/bin/ibus-daemon -d -r --panel=disable --emoji-extension=disable
+
+# steamargs+=("-steamfs")
+
+if [[ "$(cat /sys/devices/virtual/dmi/id/product_name)" =~ "Jupiter" ]]; then
+	(while true; do
+    	/usr/lib/hwsupport/powerbuttond
+	done) &
+else
+	(while true; do
+    	/usr/lib/holoiso-hwsupport/power-button-handler.py
+	done) &
 fi
 
-# Input method support if present
-if command -v /usr/bin/ibus-daemon > /dev/null; then
-    /usr/bin/ibus-daemon -d -r --panel=disable --emoji-extension=disable
+short_session_tracker_file="/tmp/steamos-short-session-tracker"
+short_session_duration=60
+short_session_count_before_reset=3
+SECONDS=0
+
+short_session_count=$(< "$short_session_tracker_file" wc -l)
+
+if [[ "$short_session_count" -ge "$short_session_count_before_reset" ]]; then
+	# TODO could detect if we're in the devkit case below and undo that instead
+	# instead of resetting the wrong thing
+	# also could print full list of files and sizes in the Steam dir and save as a diagnostic report
+	echo >&2 "gamescope-session: detected broken Steam, bootstrapping from OS copy..."
+	mkdir -p ~/.local/share/Steam
+	# remove some caches and stateful things known to cause Steam to fail to start if corrupt
+	rm -rf --one-file-system ~/.local/share/Steam/config/widevine
+	# restore clean copy of binaries from RO partition
+	tar xf /usr/lib/steam/bootstraplinux_ubuntu12_32.tar.xz -C ~/.local/share/Steam
+	# rearm
+	rm "$short_session_tracker_file"
 fi
 
-# If we have mangoapp binary start it
-if command -v mangoapp > /dev/null; then
-    mangoapp > "${HOME}"/.mangoapp-stdout.log 2>&1 &
-fi
+# This will re-send automount notifications for steam, and has a builtin timeout to wait for steam to come up.
+# _eventually_ steam should learn to talk to udisks so we don't have to rube goldberg this info to it.
+/usr/bin/steamos-polkit-helpers/steamos-retrigger-automounts
 
-# Start Steam client
-$STEAMCMD > "${HOME}"/.steam-stdout.log 2>&1
+if [[ -x $HOME/devkit-game/devkit-steam ]]; then
+	steam_notif_daemon &
+	mangoapp &
+	"$HOME"/devkit-game/devkit-steam "${steamargs[@]}"
+else
+	steam_notif_daemon &
+	mangoapp &
+	steam "${steamargs[@]}"
+fi
 
 if [[ "$SECONDS" -lt "$short_session_duration" ]]; then
-	echo "steam failed" >> "$short_session_tracker_file"
+	echo "frog" >> "$short_session_tracker_file"
 else
 	rm "$short_session_tracker_file"
 fi
 
-# When the client exits, kill gamescope nicely
+# Ask gamescope to exit nicely
 kill $gamescope_pid
 
 # Start a background sleep for five seconds because we don't trust it
 sleep 5 &
-sleep_pid="$!"
-
-# Catch reboot and poweroof sentinels here
-if [[ -e "$STEAMOS_STEAM_REBOOT_SENTINEL" ]]; then
-	rm -f "$STEAMOS_STEAM_REBOOT_SENTINEL"
-	# rearm short session tracker
-	rm "$short_session_tracker_file"
-	reboot
-fi
-if [[ -e "$STEAMOS_STEAM_SHUTDOWN_SENTINEL" ]]; then
-	rm -f "$STEAMOS_STEAM_SHUTDOWN_SENTINEL"
-	# rearm short session tracker
-	rm "$short_session_tracker_file"
-	poweroff
-fi
+sleep_pid=$!
 
 # Wait for gamescope or the sleep to finish for timeout purposes
 ret=0
@@ -322,3 +345,6 @@ for job in $(jobs -p); do
 	kill -9 "$job"
 done
 
+# This should just be waiting on kill -9'd things. Another signal will cause us to give up, but we should be a little
+# stubborn about not letting the session die with gamescope holding on to things.
+wait
